Skip to content
Search or jump to…
Pull requests
Issues
Marketplace
Explore
 
@hanWang729 
udacity
/
nd064_course_1
Public
19
2381.1k
Code
Issues
9
Pull requests
26
Actions
Projects
Wiki
Security
Insights
nd064_course_1/solutions/github-actions/docker-build.yml

Katie Gamanji Initial commit
Latest commit 1d55088 on 6 Jan
 History
 0 contributors
47 lines (42 sloc)  1.34 KB
   
## MOVE THIS FILE to `.github/workflows/docker-build.yaml` TO EXECUTE IT

# This is a basic workflow to help you get started with Actions

name: Docker Build and Push

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          platforms: linux/amd64
          push: true
          tags: pixelpotato/python-helloworld:latest
© 2021 GitHub, Inc.
Terms
Privacy
Security
Status
Docs
Contact GitHub
Pricing
API
Training
Blog
About
